version: '3'
services:
  resendmail-web:
    container_name: resendmail-web
    restart: always
    image: petermatthew/resendmail-web
    ports:
      - "${PORT}:5827"
    environment:
      - PORT=5827
      - RESEND_API_KEY=${RESEND_API_KEY}
      - SITE_PASSWORD=${SITE_PASSWORD}
